function drawHumidity(humidity) {
    var gaugeHumidity = new RadialGauge({
        renderTo: 'Humidity',
        width: 150,
        height: 150,
        units: "%",
        startAngle: 70,
        ticksAngle: 220,
        colorPlate: "#ffffff",
        colorUnits: "#909497",
        colorNumbers: "#909497",
        needleType: "arrow",
        needleStart: 0,
        needleEnd: 75,
        needleWidth: 4,
        needleCircleSize: 5,
        needleCircleInner: false,
        needleCircleOuter: true,
        needleShadow: false,
        colorNeedle: "#909497",
        colorNeedleEnd: "#909497",
        colorNeedleCircleOuter: "#909497",
        colorNeedleCircleOuterEnd: "#909497",
        //barWidth: 5,
        colorBarProgress: '#3CA7DB',
        colorBar: '#fff',
        colorMajorTicks: ["#808B96", "#ffffff", "#ffffff", "#ffffff", "#ffffff",
            "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#808B96"
        ],
        colorMinorTicks: "#ffffff",
        minValue: 0,
        maxValue: 100,
        majorTicks: ["0", "10", "20", "30", "40", "50", "60", "70", "80", "90", "100"],
        minorTicks: "10",
        strokeTicks: true,
        highlights: [{
            "from": 0,
            "to": 100,
            "color": "#808B96"
        }],
        highlightsWidth: 25,
        numbersMargin: 12,
        animation: true,
        animationRule: "linear",
        fontUnitsSize: 40,
        valueBox: true,
        valueBoxStroke: false,
        valueBoxWidth: 50,
        valueInt: 2,
        valueTestShadow: false,
        fontValueSize: 40,
        colorValueBoxRect: "#808B96",
        colorValueBoxBackground: "#D0D3D4",
        valueDec: 2,
        borders: false,
        borderShadowWidth: 0,
        value: humidity,
        animateOnInit: false,
        animatedValue: false,
        fontNumbersSize: 24,
    });
    gaugeHumidity.draw();
}