function drawTemperature(temp) {
    var gaugeTemperature = new RadialGauge({
        renderTo: 'Temperature',
        width: 150,
        height: 150,
        value: temp,
        units: "°C",
        minValue: -40,
        maxValue: 40,
        majorTicks: [-40, -30, -20, -10, 0, 10, 20, 30, 40],
        minorTicks: 5,
        strokeTicks: true,
        highlights: [{
            "from": -40,
            "to": 0,
            "color": "#2E86C1"
        }, {
            "from": 0,
            "to": 40,
            "color": "#A93226"
        }],
        highlightWidth: 25,
        tickAngle: 225,
        startAngle: 45,
        colorMajorTicks: "4d4d4d",
        colorMinorTicks: "4d4d4d",
        //colorTitle: "4d4d4d",
        colorUnits: "4d4d4d",
        colorNumbers: "4d4d4d",
        //colorPlate: "ffffff",
        colorNumbers: "4d4d4d",
        borders: false,
        needleType: "arrow",
        needleStart: 0,
        needleWidth: "2",
        needleCircleSize: 5,
        needleCircleOuter: true,
        needleCircleInner: false,
        animation: true,
        needleDuration: 750,
        animationRule: "linear",
        /*colorBorderOuter: "#333",
        colorBorderOuterEnd: "#111",
        colorBorderMiddle: "#222",
        colorBorderMiddleEnd: "#111",
        colorBorderInner: "#111",
        colorBorderInnerEnd: "#333",*/
        colorNeedleShadowDown: false,
        //colorNeedleCircleOuter: "4d4d4d",
        //colorNeedleCircleOuterEnd: "4d4d4d",
        valueBox: true,
        valueBoxStroke: false,
        valueBoxWidth: 20,
        valueInt: 2,
        valueTestShadow: false,
        fontValueSize: 40,
        colorValueBoxRect: "#808B96",
        colorValueBoxBackground: "#D0D3D4",
        valueDec: 2,
        borderShadowWidth: 0,
        animateOnInit: false,
        animatedValue: false,
        fontNumbersSize: 24,
        numberMargin: 10,
        fontUnitsSize: 40,
        fontNumbersSize: 24,
    });
    gaugeTemperature.draw();
}